### ISSUE TITLE
Missing index.js in v0.1.4 pushed to npm

### ISSUE THREAD

**Issue by brandonpapworth** [shonny-ua/gulp-extract-sourcemap#4]
The current version of gulp-extract-sourcemap (version 0.1.4 as of this posting) in NPM is missing the actual code for the module (the index.js file in this case). Therefore, the error `Error: Cannot find module 'gulp-extract-sourcemap'` is thrown when the module is required. I can get by via linking directly to the github repo in my package.json, but that doesn't help anybody who is using `npm install gulp-extract-sourcemap`.

**Comment by robshep** [comment]
+1

**Comment by shonny-ua** [comment]
Try now with v0.1.5
